### ISSUE TITLE
Installing "javascript-regex@2.0.0" failed.

### ISSUE THREAD

**Issue by dan96kid** [wizard04wsu/javascript-regex#11]
Error log:

> tree-sitter-regex-js@2.0.0 install C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12099-7828-qkl26y.f2v2b\node_modules\javascript-regex\node_modules\tree-sitter-regex-js
> node-gyp rebuild

C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12099-7828-qkl26y.f2v2b\node_modules\javascript-regex\node_modules\tree-sitter-regex-js>if not defined npm_config_node_gyp (node "C:\Users\Tribus\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Tribus\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12099-7828-qkl26y.f2v2b\node_modules\javascript-regex\node_modules\tree-sitter-regex-js\build\tree_sitter_regex_binding.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Tribus\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\Tribus\\AppData\\Local\\atom\\app-1.46.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Tribus\\AppData\\Local\\atom\\app-1.46.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12099-7828-qkl26y.f2v2b\node_modules\javascript-regex\node_modules\tree-sitter-regex-js
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Tribus\AppData\Local\Temp\apm-install-dir-12099-7828-qkl26y.f2v2b\package.json'
npm WARN apm-install-dir-12099-7828-qkl26y.f2v2b No description
npm WARN apm-install-dir-12099-7828-qkl26y.f2v2b No repository field.
npm WARN apm-install-dir-12099-7828-qkl26y.f2v2b No README data
npm WARN apm-install-dir-12099-7828-qkl26y.f2v2b No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-regex-js@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-regex-js@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tribus\.atom\.apm\_logs\2020-10-09T16_36_41_148Z-debug.log

**Comment by wizard04wsu** [comment]
Try this:
https://github.com/wizard04wsu/javascript-regex#failure-to-load-package-grammars-when-i-open-atom

If that doesn't work, please describe the steps you took before getting the error. What versions of Atom and Electron are you using?
